### PR TITLE
Include Total Points in player_stats return

### PR DESCRIPTION
**Pull request by DMcP89**
I have updated the player_stats command to leverage the League resource from the Yahoo API instead of the Player resource. This allows us to return the total points and all the stats details. There are a few other benefits IMO:

- Makes the library more predictable as the league class is now using the league resource instead of an edge case where it uses the player resource
- We are only gaining data here the league /stats endpoint returns the same values as the players /stats endpoint
- Allows us to simplify the mock for player_stats

### CODE REVIEW

**Comment by duncanduncan** [comment]
> I have updated the player_stats command to leverage the League resource from the Yahoo API instead of the Player resource. This allows us to return the total points and all the stats details. There are a few other benefits IMO:
> 
> * Makes the library more predictable as the league class is now using the league resource instead of an edge case where it uses the player resource
> * We are only gaining data here the league /stats endpoint returns the same values as the players /stats endpoint
> * Allows us to simplify the mock for player_stats

Thanks for your work on this.
Does this allow for checking against league scoring rules to product a players total fantasy points?

**Comment by DMcP89** [comment]
@duncanduncan yes the total points is based off the scoring of the league. The point calculation is done by the Yahoo API not the library so it will always match what's listed in the Yahoo app/site

**Comment by DMcP89** [comment]
@spilchen Can this be merged?

**Review by spilchen — APPROVED** [review]
Looks good. Thanks for contributing again.

**Pull request merged**
